from tkinter import filedialog, PhotoImage
import cv2 as cv
from tkinter.messagebox import showwarning
from PIL import Image as PILimage
class PhotoManage:
	def imgBin(imglocation):
		with open(imglocation,'rb') as f:
			datainbin=f.read()
			f.close()
			return datainbin
	def BinToImage(imgbinaryData):
		imageName='media/binimages/SMS BInImage'+'.png'
		with open(imageName,'wb') as f:
			f.write(imgbinaryData)
			f.close()
			return imageName
	def TakePhoto(tagname):
		camport = 0
		camera = cv.VideoCapture(camport)
		while True:
			returnVal,img = camera.read() #read image
			cv.imshow('Camera, Press q to capture', img) #show image in window
			key=cv.waitKey(1)  #wait for key press 
			if key==ord('q'): # qiut is pressed q
				break
		cv.destroyAllWindows()
			# first returning is True or False and second is numpy okect of image
		imageName=r'media/binimages/SMS Generated Image by camera'+'.png'
		cv.imwrite(imageName,img)
		del(camera)
		#resize the image to add into tkinter window
		resizedImage= PILimage.open(imageName).resize((300,413))   #dimension of image width x height
		resizedImage.save(imageName)
		image=PhotoImage(file=imageName).subsample(2,2)
		tagname.config(image=image)
		tagname.image=image
		return imageName
	def choosePhoto(tagname):
		imageName=r'media/binimages/SMS Generated by Files'+'.png'
		path=filedialog.askopenfilename()
		if path == '':   #chage the image directory if no images choosed from files... 
			return ''
		#resize the image to add into tkinter window
		else:
			try:
				resizedImage= PILimage.open(path).resize((300,413))   #dimension of image width x height
				resizedImage.save(imageName)
				image=PhotoImage(file=imageName).subsample(2,2)   #initiating too add image to the label..
				tagname.config(image=image) #configureation to the label 
				tagname.image=image
				return imageName
			except:
				showwarning(message='Invalid  Image type')
	def setPhoto(tagname,imglocation,sb1=3,sb2=3):
		#resize the image to add into tkinter window
		resizedImage= PILimage.open(imglocation).resize((413,413))   #dimension of image width x height
		resizedImage.save(imglocation)
		image=PhotoImage(file=imglocation).subsample(sb1,sb2)   #initiating too add image to the label..
		tagname.config(image=image) #configureation to the label 
		tagname.image=image